# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-15 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_default_reimb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='lennyface',
        ),
    ]
